### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by AA666666**

### CODE REVIEW

**Comment by AA666666** [comment]
Please approve it if you have a chance

**Comment by AA666666** [comment]
thanks

**Comment by AA666666** [comment]
I can add more details for the recent two weeks if you think it is too simple

**Comment by JadenBalogh** [comment]
> I can add more details for the recent two weeks if you think it is too simple

The ideal level of detail is enough so that someone who missed the meeting could read the notes and understand what happened in the meeting. I don't think you have enough detail yet. You should specify things like "reviewed the website" with specific notes like "the about page has some formatting issues which are going to be reviewed today".

**Review by JadenBalogh — CHANGES_REQUESTED** [review]
Needs more detail. See above comment.

**Comment by AA666666** [comment]
Thanks for the comments. I will modify it.

**Comment by AA666666** [comment]
done editing the note, please approve it if you have a chance. Thanks. Best of luck on your exams everyone:)

**Review by JadenBalogh — APPROVED** [review]
Details are getting better; it would still be nice to have more bullet points for what we did during each time stamp for future notes (for example, "finalized the description of the heuristics graph for the peer testing 1 report").

**Review by aKrisnanto — APPROVED** [review]

**Pull request merged**
