### PR TITLE
Add logo mockups

### PR DESCRIPTION
**Pull request by JadenBalogh**

### CODE REVIEW

**Comment by JadenBalogh** [comment]
Really a fan of Prototype 3! Nice work.

**Comment by Jaredhw** [comment]
Logo mock-ups look good, still not sure why the github preview doesn't show text.

**Comment by aKrisnanto** [comment]
Everything looks good so far

**Review by Jaredhw — APPROVED** [review]

**Comment by AA666666** [comment]
Prototypes are creative

**Review by AA666666 — APPROVED** [review]

**Pull request merged**
