### PR TITLE
Signup and Login page

### PR DESCRIPTION
**Pull request by aKrisnanto**

### CODE REVIEW

**Review by JadenBalogh — APPROVED** [review]
Looks good!

**Review by AA666666 — APPROVED** [review]

**Comment by AA666666** [comment]
well done thanks Alvin

**Review by Jaredhw — APPROVED** [review]
Nice, got everything, as per the meeting with Twila we'll have to add the appearing text-boxes but that's not relevant to this code. We will also need to add a postal code field for Google Maps integration.

**Review by JadenBalogh — APPROVED** [review]
Looks good, keep in mind comments from the meeting today for this week: move large data chunks to external files (like years) - or find premade components to solve these problems, potentially move Form component into the parent, get functionality working (as per #152), etc.

**Pull request merged**
