### PR TITLE
Update front end

### PR DESCRIPTION
**Pull request by AA666666**

### CODE REVIEW

**Comment by AA666666** [comment]
changes done. Ready for review

**Review by Jaredhw — APPROVED** [review]
Tons done, I may need your help parsing it all for the sprint next week haha!

**Comment by AA666666** [comment]
Happy to help :)

> Tons done, I may need your help parsing it all for the sprint next week haha!

Happy to help:)

**Review by JadenBalogh — APPROVED** [review]
This PR is stable on its own but does not merge cleanly into our existing codebase. I am approving it to be merged into a `prototype` branch for use in demos and as a reference for front-end styling for our working code.

**Pull request merged**
