### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by AA666666**
Changes done, ready for review. Thanks.

### CODE REVIEW

**Comment by AA666666** [comment]
If you guys think today's meeting note is not specific, I will record more details in the next meeting. Thanks

**Comment by JadenBalogh** [comment]
> If you guys think today's meeting note is not specific, I will record more details in the next meeting. Thanks

The meeting notes are definitely improving! I know it can be hard to write notes and pay attention at the same time, but if possible a huge improvement would be to mention exact details instead of vague notes.

**Not very helpful:**
> Discussing Jared's progress(database implementation)

**More helpful:**
> Discussed Jared's progress over the break:
> - completed the rest of the database implementation based on Twila's documentation
> - potentially need to update some tables to fit the new authentication code
> - Jared has been unavailable due to personal reasons which kept him away from the house
> - planning to push all the db changes when he gets home on Tuesday or Wednesday

**Review by JadenBalogh — APPROVED** [review]
Notes are sufficient for this week. Take a look at my comments for an example of how these could be improved further.

**Comment by AA666666** [comment]
Thanks for your advices Jaden

**Review by Jaredhw — APPROVED** [review]
Looks good. I'll add the design drafts discussed tomorrow/tonight.

**Comment by AA666666** [comment]
Thanks Jared

**Pull request merged**
