### PR TITLE
update members' visibility, clear filter function of member page, number fields

### LINKED ISSUE #284: Members should not be able to see themselves in the search page

### LINKED ISSUE #285: Members filter panel should have a “clear filters” button

### LINKED ISSUE #286: Number fields should not go negative

### PR DESCRIPTION
**Pull request by AA666666**
Closes #284, closes #285, closes #286

### CODE REVIEW

**Comment by AA666666** [comment]
Changes done

**Comment by AA666666** [comment]
Please review it when you have a chance, thank you

**Review by JadenBalogh — CHANGES_REQUESTED** [review]
So far this PR is in a partially-functioning state. I have made changes to clean up some unused code and fix the functionality issues. However, the following features still need to be completed:
 - Members "clear filters" button does not clear the search bar
 - The rest of the number fields across the site still need to be changed

**Comment by AA666666** [comment]
Thanks Jaden. I thought I only need to clear the filter. Do you think it's necessary to clear the search bar? Besides, where are the number fields I need to change except the ones I have changed?

**Comment by JadenBalogh** [comment]
> Thanks Jaden. I thought I only need to clear the filter. Do you think it's necessary to clear the search bar? Besides, where are the number fields I need to change except the ones I have changed?

I suppose it's fine to only clear the filter panel.

As far as the number fields, they are on many of our forms, such as signup. Try looking through the site to find where they exist, or search the code for `type='number'`.

**Comment by AA666666** [comment]
Thanks for the comments. I think I have changed the min/ max HomeCapacity, min/max MonthlyBudget on sign up page and members page. Is there anything else I need to change?

**Comment by JadenBalogh** [comment]
> Thanks for the comments. I think I have changed the min/ max HomeCapacity, min/max MonthlyBudget on sign up page and members page. Is there anything else I need to change?

I'm not sure off the top of my head. I would suggest double-checking using the method I mentioned above, if you haven't already.

**Comment by AA666666** [comment]
Thanks. I double-checked using the method type='number,' and the stuffs showed up are min/ max HomeCapacity, min/max MonthlyBudget on sign up page and members page

**Comment by JadenBalogh** [comment]
> Thanks. I double-checked using the method type='number,' and the stuffs showed up are min/ max HomeCapacity, min/max MonthlyBudget on sign up page and members page

Ok, go ahead and commit your changes once you're done and I'll review them.

**Comment by AA666666** [comment]
I have done it in my previous commit:)

**Comment by JadenBalogh** [comment]
> I have done it in my previous commit:)

I see, it looks like the Edit Member form is out of date and doesn't have these updated fields. We'll need to review that in a separate issue.

**Review by JadenBalogh — APPROVED** [review]
Approved. Note that we'll need to review the Edit Profile page to have the most recent fields as per Twila's specs.

**Review by aKrisnanto — APPROVED** [review]
Seems good, only minor issue I found was that clicking the checkbox text instead of the checkbox (eg. 'pet friendly') gave the visual feedback of it being clicked but not having the checkbox toggle.

**Pull request merged**
