### PR TITLE
Update backend

### PR DESCRIPTION
**Pull request by AA666666**

### CODE REVIEW

**Review by JadenBalogh — APPROVED** [review]
This PR deletes the entirety of our progress from the past five months, contains only a server-side with almost none of our existing code, and appears to follow a completely different project structure. However, I will approve it to be merged into the `prototype` branch.

**Comment by AA666666** [comment]
I deleted some code unintentionally

**Comment by AA666666** [comment]
When I did git push, I accidentally deleted other code

**Comment by JadenBalogh** [comment]
Ok, feel free to revert any unintentional changes. Please make any needed changes ASAP though, as I will be running GitStats in the next hour or so.

**Comment by AA666666** [comment]
The structure is for you to compare, if you think it's better then we can follow it, if you insist I can follow your structure

**Pull request merged**
